apiVersion: v1
kind: Service
metadata:
  name: trekky-hub-service
  labels:
    app: trekky-hub
spec:
  type: NodePort
  selector:
    app: trekky-hub
  ports:
    - protocol: TCP
      port: 80            # Service port
      targetPort: 3000    # Container port (change to 8000 if backend only)
      nodePort: 30007     # External access port
